### ISSUE TITLE
secret 관련 cli tool 신규 제공

### ISSUE THREAD

**Issue by djinchung** [fatima-go/fatima-cmd#1]
[필요성]
다음의 기능 개선 사항과 관련하여 cli 로 secret 을 생성하거나 복호화해볼 수 있는 툴이 필요함
[config 처리시 encrypt 기능 제공](https://github.com/fatima-go/fatima-core/issues/1)

[작업방향]
cli tool 은 로컬에서만 사용되니 **`lc`** 라는 이름의 프리픽스로 시작한다.
```shell
lccrypt enc "hello world"
lccrypt dec my_cipher_text
```

**Comment by bestpop** [comment]
@djinchung 티켓 넘겨 드립니다.
잘 부탁 드립니다

**Comment by djinchung** [comment]
@wideDoor 본 이슈 넘겨 드립니다. 
enc 할때는 b64, native 중 방법을 받아야 할거 같고..
Fatima-core v1.1.1 참고하시면 관련된 코드 (e.g CreateSecretNative() ) 있으니 참고해 될듯 하구요..
dec 할때는 Fatima-core 의 ResolveSecret 사용하면 될거 같네요..
