### ISSUE TITLE
roproc 원격으로 실행 안되는 버그 수정

### ISSUE THREAD

**Issue by jiaekim123** [fatima-go/fatima-cmd#3]
-p 옵션으로 실행 시 remove / add 불가한 버그

```bash
roproc -p spot01.prod remove {package_name}
2023-08-10 15:50:00 (Asia/Seoul)
UnRegist juno. total=0, success=0
```

**Comment by djinchung** [comment]
네 본 건은 제가 확인해 보도록 할께요

**Comment by djinchung** [comment]
아니면.. jupiter에 config  설정을 통해서 roproc, rostop, rostart 등의 원격 명령어 허용/막는 옵션 넣어두자~ 
이렇게 해서 상용은 막고, dev, qa 등은 허용하는걸로 (default 는 허용)
